### PR TITLE
Add node.js v10 support

### LINKED ISSUE #599: cannot install in node.js@10.0.0
node.js@10.0.0 came out yesterday and after upgrading to 10.0.0

`npm i bcrypt` makes an error

```
ode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zerocho/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/zerocho/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
```

### LINKED ISSUE #600: node 10.0.0 compatibility
Are there plans to support node 10.0.0 anytime soon?

### PR DESCRIPTION
**Pull request by pauliusuza**
I merged in the changes by @4ware from #601 
fixes #600 
fixes #599

### CODE REVIEW

**Comment by pauliusuza** [comment]
@agathver all builds are green

**Comment by agathver** [comment]
Thank you so much @pauliusuza

**Comment by et** [comment]
Does a new release need to be published?
Pulling the latest version of `bcrypt` with node 10 still fails with:
```
> bcrypt@2.0.1 install /Users/et/code/NeatCapitalOrg/server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v2.0.1/bcrypt_lib-v2.0.1-node-v64-darwin-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@2.0.1 and node@10.1.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
```

**Comment by et** [comment]
Friendly ping @agathver. Can you please publish a new release?

**Comment by agathver** [comment]
OSX Binaries were not available. It failed to upload from travis. No worries, I'll trigger the build again.

_However, remember that pre-built binaries are only provided on a best effort basis._

**Comment by et** [comment]
Thank you @agathver. The latest build is working for me 😄
