### ISSUE TITLE
bcrypt.js failed to download and build on Centos 6.2 via npm

### ISSUE THREAD

**Issue by ferasodh** [kelektiv/node.bcrypt.js#78]
I'm trying to download bcrypt with npm but it fails with the following error:

../src/bcrypt_node.cc: In function 'void crypto_lock_init()':
../src/bcrypt_node.cc:87: error: 'CRYPTO_num_locks' was not declared in this scope
../src/bcrypt_node.cc:92: error: 'abort' was not declared in this scope
../src/bcrypt_node.cc: In function 'void crypto_lock_cb(int, int, const char_, int)':
../src/bcrypt_node.cc:96: error: 'CRYPTO_LOCK' was not declared in this scope
../src/bcrypt_node.cc:97: error: 'CRYPTO_READ' was not declared in this scope
../src/bcrypt_node.cc:98: error: 'CRYPTO_WRITE' was not declared in this scope
../src/bcrypt_node.cc: In function 'int<unnamed>::GetSeed(uint8_t_, int)':
../src/bcrypt_node.cc:141: error: 'RAND_bytes' was not declared in this scope
../src/bcrypt_node.cc:144: error: 'RAND_pseudo_bytes' was not declared in this scope
../src/bcrypt_node.cc: In function 'bool<unnamed>::ValidateSalt(const char_)':
../src/bcrypt_node.cc:187: error: 'atoi' was not declared in this scope
../src/bcrypt_node.cc: In function 'void init(v8::Handlev8::Object)':
../src/bcrypt_node.cc:479: error: 'CRYPTO_set_locking_callback' was not declared in this scope
../src/bcrypt_node.cc:480: error: 'CRYPTO_set_id_callback' was not declared in this scope
Waf: Leaving directory `/root/wowito/wowito/node_modules/bcrypt/build'
Build failed:  -> task failed (err #1):
        {task: cxx bcrypt_node.cc -> bcrypt_node_1.o}
make: *_\* [compile] Error 1
npm http GET https://registry.npmjs.org/nodemailer/-/nodemailer-0.1.20.tgz

npm ERR! bcrypt@0.5.0 install: `make build`
npm ERR! `sh "-c" "make build"` failed with 2
npm ERR!
npm ERR! Failed at the bcrypt@0.5.0 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 2.6.18-028stab095.1
npm ERR! command "nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/wowito/wowito
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.16
npm ERR! code ELIFECYCLE
npm ERR! message bcrypt@0.5.0 install: `make build`
npm ERR! message `sh "-c" "make build"` failed with 2
npm ERR! errno {}

How can I solve this issue?
Thanks,
Feras

**Comment by megkcalb** [comment]
I have the same issue over here. Anyone find the solution ?
