### ISSUE TITLE
Expected in: flat namespace

### ISSUE THREAD

**Issue by XWindMan** [kelektiv/node.bcrypt.js#792]
dir:node_modules/bcrypt/examples

node forever_gen_salt.js 

dyld: lazy symbol binding failed: Symbol not found: _napi_add_finalizer
  Referenced from: /Users/developer/Desktop/Life/MyCode/wmNode/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  Expected in: flat namespace

dyld: Symbol not found: _napi_add_finalizer
  Referenced from: /Users/developer/Desktop/Life/MyCode/wmNode/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  Expected in: flat namespace

Abort trap: 6

**Comment by XWindMan** [comment]
Only 3.0.0 version does not have this problem, node 10 version can be installed, other node versions may not be installed, nvm can be switched to node 10

**Comment by a4xrbj1** [comment]
Had the same problem after upgrading from 3.0.7 to 4.0 - now as soon as I went back to 3.0.7 it works again

**Comment by agathver** [comment]
@XWindMan Can you please report your exact NodeJS version?

**Comment by allanext** [comment]
Working for me with node 12 and bcrypt 3.0.7

**Comment by a4xrbj1** [comment]
For me it’s Node 13.8 and version 4.0.8 produces this error, 3.0.7 works indeed

Andreas
