### ISSUE TITLE
cannot install in node.js@10.0.0

### ISSUE THREAD

**Issue by ZeroCho** [kelektiv/node.bcrypt.js#599]
node.js@10.0.0 came out yesterday and after upgrading to 10.0.0

`npm i bcrypt` makes an error

```
ode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/zerocho/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/zerocho/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
```

**Comment by dylanpyle** [comment]
@ZeroCho I had this exact issue with an older version of bcrypt we were using (0.8.7), but updating to 2.0.1 fixed it for me

**Comment by ZeroCho** [comment]
@dylanpyle Thank you! Upgrading to bcrypt@^2.0.1 solved the problem.

**Comment by subatomicglue** [comment]
Still seeing this in MacOSX 10.13.4 High Sierra with node 10.0 and npm 5.6 and bcrypt 2.0.1

I listed the errors (similar to above) here:
https://github.com/kelektiv/node.bcrypt.js/issues/600

**Comment by ZeroCho** [comment]
@pauliusuza Have you tried `npm rebuild`?

**Comment by pauliusuza** [comment]
Yes, and followed instructions on github on setup. Build still fails

**Comment by deksden** [comment]
Same issue for me with node 10.5 and bcrypt 2.0.1 on macOS

**Comment by pags** [comment]
This is still an issue with Node.js 10 and Bcrypt 3.0.3. Will this ever be fixed?
