### ISSUE TITLE
bcrypt not working in current node 9.3.0

### ISSUE THREAD

**Issue by inhaq** [kelektiv/node.bcrypt.js#566]
Hi,

when i run npm install and run my project, it doesn't install bcrypt whereas all other dependencies are installed.

module.js:557
    throw err;
    ^

Error: Cannot find module 'E:****\node_modules\bcrypt\lib\binding\bcrypt_lib.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\*******\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\******\app\models\user.model.js:4:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

**Comment by agathver** [comment]
You need to compile the module. Run `npm rebuild bcrypt`

**Comment by inhaq** [comment]
I tried several ways, not the one you mentioned above. But after all failures, i downgrade node to 8.9.3 version and npm to under 5. Then delete all node modules and first install bcrypt and then install all other modules. That trick did work.

**Comment by agathver** [comment]
NodeJS 9 and npm have weird issues. Please stick to NodeJS 8 till all of them are resolved.

**Comment by alexmac131** [comment]
it don't work in nodejs 9 use 8 is the answer - no that is not an answer that's excuse.

**Comment by agathver** [comment]
@alexmac131 I understand your frustration, but sometimes npm breaks after new Node releases and all we can do is wait for them to fix it.

Good news it bcrypt now works fine with NodeJS 9 and the latest version of NPM. We also have published the pre-built binaries for Linux and macOS.

**Comment by alexmac131** [comment]
Solution change from bcrypt to bcryptjs  - working

**Comment by agathver** [comment]
If you want to block your event loop, then yes

**Comment by Shishoo** [comment]
node version: **14.16.0 (LTS)**
npm version:  **6.14.11**
OS: **Windows 10**

I get the following error:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^
 
Error: Cannot find module '...path...\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node'
Require stack:
- ...path...\node_modules\bcrypt\bcrypt.js
- ...path...\crypto.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (...path...\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...path...\\node_modules\\bcrypt\\bcrypt.js',
    '...path...\\crypto.js'
  ]
}
```

I have tried the fixes here and [here](https://github.com/kelektiv/node.bcrypt.js/issues/800) and haven't been able to resolve the issue.  PS... @recrsn ...I don't want to block the event loop :)
