### ISSUE TITLE
node 7.7.0 build fails

### ISSUE THREAD

**Issue by jhen0409** [kelektiv/node.bcrypt.js#492]
* Which version of nodejs and OS?

node 7.7.0 and Linux (Travis CI) / macOS 10.12.4

```
make: Entering directory `/home/travis/build/<project>/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../../nan/nan.h:47:0,
                 from ../src/bcrypt_node.cc:1:
/home/travis/.node-gyp/7.7.0/include/node/node.h:44:33: fatal error: tracing/trace_event.h: No such file or directory
 #include "tracing/trace_event.h"
                                 ^
compilation terminated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/travis/build/<project>/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v7.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v7.7.0/bin/node" "/home/travis/.nvm/versions/node/v7.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/<project>/node_modules/bcrypt
gyp ERR! node -v v7.7.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

Just happened on my CI build.

**Comment by Lokgic** [comment]
Had the same issue on heroku. Things are fine after reverting back to 7.6.0

**Comment by jeffijoe** [comment]
I can't build on 7.6.0

**Comment by jhen0409** [comment]
Look like it's node issue: https://github.com/nodejs/node/issues/11628.

**Comment by jhen0409** [comment]
node 7.7.1 fixed this. :)

**Comment by IgorGanapolsky** [comment]
@jhen0409  No it didn't.  I still get this with Node 7.7.2:
> gyp ERR! cwd /home/eazyigz/workspace/crestron/locus_bridge_emu_node/node_modules/usb
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
