### ISSUE TITLE
'nan_callbacks.h' file not found

### ISSUE THREAD

**Issue by iTonyYo** [kelektiv/node.bcrypt.js#718]
```shell
In file included from ../src/bcrypt_node.cc:1:                                        git:(develop|✚4…
../../nan/nan.h:148:10: fatal error: 'nan_callbacks.h' file not found
#include "nan_callbacks.h"  // NOLINT(build/include)
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
```
- - - 
os: macOS Mojave v10.14.4
node: v10.15.3
npm: v6.9.0

**Comment by agathver** [comment]
npm should have downloaded prebuilt binaries for you. 

What is the version of bcrypt? Node 10 will not work with versions less than 3.0

**Comment by YasharF** [comment]
Is this still an issue? Can this be marked as resolved?

**Comment by hansiemithun** [comment]
I am facing similar issue, found any resolutions to this?

```
../../nan/nan.h:148:10: fatal error: 'nan_callbacks.h' file not found
#include "nan_callbacks.h"  // NOLINT(build/include)
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/apple/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/apple/.nvm/versions/node/v10.14.2/bin/node" "/Users/apple/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/apple/Documents/projects/sailssample/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/apple/Documents/projects/sailssample/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/apple/Documents/projects/sailssample/node_modules/bcrypt
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
node: `v10.14.2`
npm: `6.4.1`
