### ISSUE TITLE
cannot install on redhat using node js 11.12 and npm version1.4.3

### ISSUE THREAD

**Issue by smartmouse** [kelektiv/node.bcrypt.js#220]
Similar issues as  ---Won't install on OS X with gcc (node-gyp rebuild error) #217 
it was working fine on  node js10.26.

[nodebot@jtcjs04 testBcrypt]$ npm install bcrypt
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.7 install /home/nodebot/testBcrypt/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/home/nodebot/testBcrypt/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc:202: error: variable or field âGenSaltAsyncâ declared void
../src/bcrypt_node.cc:202: error: âuv_work_tâ was not declared in this scope
../src/bcrypt_node.cc:202: error: âreqâ was not declared in this scope
../src/bcrypt_node.cc:487: error: expected â}â at end of input
../src/bcrypt_node.cc:85: warning: âvoid crypto_lock_init()â defined but not used
../src/bcrypt_node.cc:95: warning: âvoid crypto_lock_cb(int, int, const char*, int)â defined but not used
../src/bcrypt_node.cc:105: warning: âlong unsigned int crypto_id_cb()â defined but not used
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory`/home/nodebot/testBcrypt/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodebot/jenkins_nodes/IBMSVT64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1045:12)
gyp ERR! System Linux 2.6.32-431.1.2.el6.x86_64
gyp ERR! command "node" "/home/nodebot/jenkins_nodes/IBMSVT64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodebot/testBcrypt/node_modules/bcrypt
gyp ERR! node -v v0.11.12
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.1.2.el6.x86_64
npm ERR! command "/home/nodebot/jenkins_nodes/IBMSVT64/bin/node" "/home/nodebot/jenkins_nodes/IBMSVT64/bin/npm" "install" "bcrypt"
npm ERR! cwd /home/nodebot/testBcrypt
npm ERR! node -v v0.11.12
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nodebot/testBcrypt/npm-debug.log
npm ERR! not ok code 0
[nodebot@jtcjs04 testBcrypt]$
