### ISSUE TITLE
Broken on 0.11?

### ISSUE THREAD

**Issue by stephen-fanfair** [kelektiv/node.bcrypt.js#206]
I can't seem to get bcrypt to build on 0.11. I just tried `npm i bcrypt` on an Ubuntu VM and it gave me this. Looking at the code, it seems like a really odd error--the code looks fine. Ideas?

```
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.7 install /home/vagrant/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/home/vagrant/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc:202:19: error: variable or field ‘GenSaltAsync’ declared void
../src/bcrypt_node.cc:202:19: error: ‘uv_work_t’ was not declared in this scope
../src/bcrypt_node.cc:202:30: error: ‘req’ was not declared in this scope
../src/bcrypt_node.cc:487:30: error: expected ‘}’ at end of input
../src/bcrypt_node.cc:85:13: warning: ‘void crypto_lock_init()’ defined but not used [-Wunused-function]
../src/bcrypt_node.cc:95:13: warning: ‘void crypto_lock_cb(int, int, const char*, int)’ defined but not used [-Wunused-function]
../src/bcrypt_node.cc:105:22: warning: ‘long unsigned int crypto_id_cb()’ defined but not used [-Wunused-function]
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/vagrant/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/v0.11.10/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:862:12)
gyp ERR! System Linux 3.8.0-35-generic
gyp ERR! command "node" "/home/vagrant/.nvm/v0.11.10/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/node_modules/bcrypt
gyp ERR! node -v v0.11.10
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-35-generic
npm ERR! command "/home/vagrant/.nvm/v0.11.10/bin/node" "/home/vagrant/.nvm/v0.11.10/bin/npm" "i" "bcrypt"
npm ERR! cwd /home/vagrant
npm ERR! node -v v0.11.10
npm ERR! npm -v 1.3.22
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/npm-debug.log
npm ERR! not ok code 0
```
